
###
POST http://localhost:3000/movies
Authorization: basic anVhbi5nYXJuaWNhKzFAaG9sYS5jb206MTIzNDU2YUE=
Content-Type: application/json

{
  "title": "La vide de brian",
  "year": 1997,
  "director": "los los cohen",
  "genre": "Comedy",
  "rating": 7.8
}

###
GET http://localhost:3000/movies
Authorization: basic anVhbi5nYXJuaWNhKzFAaG9sYS5jb206MTIzNDU2YUE=

###

GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZDAwZjcxZDktYThiMC00NGNjLThlNTMtOWY3MDk4YzE3ZGMwIiwiZW1haWwiOiJqdWFuLmdhcm5pY2ErMUBob2xhLmNvbSIsImlhdCI6MTY2NzU1NTc0M30.xgTSwrJvjF2QMg1bKH-xlDOak4P7XI9YT5dU3fMi8qg



###

GET http://localhost:3000/movies?title=La vide de brian
Authorization: basic QWxsYWRpbjpvcGVuIHNlc2FtZQ==


###
GET http://localhost:3000/movies/32552867-4d57-43f4-8788-406f336431cd
Authorization: basic QWxsYWRpbjpvcGVuIHNlc2FtZQ==

###
PUT http://localhost:3000/movies/32552867-4d57-43f4-8788-406f336431cd
Authorization: basic QWxsYWRpbjpvcGVuIHNlc2FtZQ==
Content-Type: application/json

{
  "title": "Airbag",
  "year": 1997,
  "director": "Ulloa",
  "rating": 7.8
}

###
PATCH http://localhost:3000/movies/32552867-4d57-43f4-8788-406f336431cd
Authorization: basic QWxsYWRpbjpvcGVuIHNlc2FtZQ==
Content-Type: application/json

{
  "genre": "Comedy",
  "rating": 9.7

}

###
DELETE http://localhost:3000/movies/32552867-4d57-43f4-8788-406f336431cd
Authorization: basic QWxsYWRpbjpvcGVuIHNlc2FtZQ==
